apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vm
spec:
  generators:
  - clusters: {}
    list:
      elements:
      - appName: dev-vm
        gitPath: dev
        namespace: dev-vm
      - appName: prod-vm
        gitPath: prod
        namespace: prod-vm
  template:
    metadata:
      name: {{appName}}
    spec:
      project: default
      source:
        repoURL: https://github.com/rh-mobb/rosa-virt-gitops.git
        targetRevision: HEAD
        path: "applicationsets/demo-vm/kustomize/{{gitPath}}"
      destination:
        server: "{{server}}"
        namespace: {{namespace}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
