apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: dev-

          #cloud-config
patches:
- patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 2Gi
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/userData
        value: |-
          #cloud-config
          user: fedora
          password: fedora123
          chpasswd: { expire: False }
  target:
    kind: VirtualMachine
resources:
- ../base
